/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as GatedRouteImport } from './routes/_gated'
import { Route as GatedIndexRouteImport } from './routes/_gated.index'
import { Route as GatedProductionRouteImport } from './routes/_gated.production'
import { Route as GatedOfficeRouteImport } from './routes/_gated.office'
import { Route as GatedDevRouteImport } from './routes/_gated.dev'
import { Route as GatedAdminRouteImport } from './routes/_gated.admin'
import { Route as GatedProductionPrintIdRouteImport } from './routes/_gated.production.print.$id'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedRoute = GatedRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedIndexRoute = GatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GatedRoute,
} as any)
const GatedProductionRoute = GatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => GatedRoute,
} as any)
const GatedOfficeRoute = GatedOfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => GatedRoute,
} as any)
const GatedDevRoute = GatedDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => GatedRoute,
} as any)
const GatedAdminRoute = GatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => GatedRoute,
} as any)
const GatedProductionPrintIdRoute = GatedProductionPrintIdRouteImport.update({
  id: '/print/$id',
  path: '/print/$id',
  getParentRoute: () => GatedProductionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof GatedIndexRoute
  '/unlock': typeof UnlockRoute
  '/admin': typeof GatedAdminRoute
  '/dev': typeof GatedDevRoute
  '/office': typeof GatedOfficeRoute
  '/production': typeof GatedProductionRouteWithChildren
  '/production/print/$id': typeof GatedProductionPrintIdRoute
}
export interface FileRoutesByTo {
  '/unlock': typeof UnlockRoute
  '/admin': typeof GatedAdminRoute
  '/dev': typeof GatedDevRoute
  '/office': typeof GatedOfficeRoute
  '/production': typeof GatedProductionRouteWithChildren
  '/': typeof GatedIndexRoute
  '/production/print/$id': typeof GatedProductionPrintIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_gated': typeof GatedRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_gated/admin': typeof GatedAdminRoute
  '/_gated/dev': typeof GatedDevRoute
  '/_gated/office': typeof GatedOfficeRoute
  '/_gated/production': typeof GatedProductionRouteWithChildren
  '/_gated/': typeof GatedIndexRoute
  '/_gated/production/print/$id': typeof GatedProductionPrintIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unlock'
    | '/admin'
    | '/dev'
    | '/office'
    | '/production'
    | '/production/print/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unlock'
    | '/admin'
    | '/dev'
    | '/office'
    | '/production'
    | '/'
    | '/production/print/$id'
  id:
    | '__root__'
    | '/_gated'
    | '/unlock'
    | '/_gated/admin'
    | '/_gated/dev'
    | '/_gated/office'
    | '/_gated/production'
    | '/_gated/'
    | '/_gated/production/print/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GatedRoute: typeof GatedRouteWithChildren
  UnlockRoute: typeof UnlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/': {
      id: '/_gated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof GatedIndexRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/production': {
      id: '/_gated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof GatedProductionRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/office': {
      id: '/_gated/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof GatedOfficeRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/dev': {
      id: '/_gated/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof GatedDevRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/admin': {
      id: '/_gated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof GatedAdminRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/production/print/$id': {
      id: '/_gated/production/print/$id'
      path: '/print/$id'
      fullPath: '/production/print/$id'
      preLoaderRoute: typeof GatedProductionPrintIdRouteImport
      parentRoute: typeof GatedProductionRoute
    }
  }
}

interface GatedProductionRouteChildren {
  GatedProductionPrintIdRoute: typeof GatedProductionPrintIdRoute
}

const GatedProductionRouteChildren: GatedProductionRouteChildren = {
  GatedProductionPrintIdRoute: GatedProductionPrintIdRoute,
}

const GatedProductionRouteWithChildren = GatedProductionRoute._addFileChildren(
  GatedProductionRouteChildren,
)

interface GatedRouteChildren {
  GatedAdminRoute: typeof GatedAdminRoute
  GatedDevRoute: typeof GatedDevRoute
  GatedOfficeRoute: typeof GatedOfficeRoute
  GatedProductionRoute: typeof GatedProductionRouteWithChildren
  GatedIndexRoute: typeof GatedIndexRoute
}

const GatedRouteChildren: GatedRouteChildren = {
  GatedAdminRoute: GatedAdminRoute,
  GatedDevRoute: GatedDevRoute,
  GatedOfficeRoute: GatedOfficeRoute,
  GatedProductionRoute: GatedProductionRouteWithChildren,
  GatedIndexRoute: GatedIndexRoute,
}

const GatedRouteWithChildren = GatedRoute._addFileChildren(GatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  GatedRoute: GatedRouteWithChildren,
  UnlockRoute: UnlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
